### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by Lalli17** [HasanAlpCaferoglu/E-SQL#4]
I am a student and want to learn your code, but I am facing difficulties in finding the data set with respective folders, can you help in attach the exact link of the dataset and also the folders with same structure

**Comment by bnsimha** [comment]
> I am a student and want to learn your code, but I am facing difficulties in finding the data set with respective folders, can you help in attach the exact link of the dataset and also the folders with same structure

I second this issue.

**Comment by HasanAlpCaferoglu** [comment]
You can access the dataset from the official BIRD-SQL Benchmark website. To run the E-SQL code, please organize the dataset as outlined in the README file.
